### ISSUE TITLE
JS Execute + Mongo command

### ISSUE THREAD

**Issue by tothradoslav** [DrMongo/DrMongo#1]
- add tabs for each collection page
1. Documents
2. Mongo commands
3. JS eval code

**Comment by tothradoslav** [comment]
I will create the tabs and layout, please wait...

**Comment by achtan** [comment]
no tabs, as we discussed

**Comment by wzoom** [comment]
Guys, awesome project, keep it up! :+1: 
Just note, I would appreciate if there is some JS console "Robomongo style" that you can write simple JS scripts for mongo.
So instead of 
<img width="549" alt="screen shot 2015-11-27 at 09 10 47" src="https://cloud.githubusercontent.com/assets/515269/11436650/f19223fa-94e6-11e5-9b03-3337b410f15e.png">

it would be simple editable textarea where I can write, ie:

```
db.Orders.find({}).forEach(function(order){
    print(order.type + order.state)
    Orders.update(order.id, {$set: {created: new Date()}})
})
```

Which is btw the most powerful feature of Robomongo

**Comment by achtan** [comment]
yes, we are working on this one

**Comment by JuanCrg90** [comment]
+1

**Comment by achtan** [comment]
Dr. Mongo is **deprecated**. Please visit our new desktop app [Dr. Mingo](http://www.drmingo.com/).
