### ISSUE TITLE
Click on "_id" has no result - deal with it :)

### ISSUE THREAD

**Issue by tothradoslav** [DrMongo/DrMongo#48]
- sometimes it looks like an ID but is not...

**Comment by JackAdams** [comment]
Anything alphanumeric with 17 characters is considered to be an _id.  Is there a better way to do this?

**Comment by achtan** [comment]
yes, here is the current matcher https://github.com/DrMongo/DrMongo/blob/372c2c46070e254d2baa09aac4e12cd63a35dc52/lib/helpers.js#L101 

do you have any suggestion how to improve this matching?

**Comment by JackAdams** [comment]
Yes, I looked up that function (because it provides half the magic I love -- the other half being in the `findCollectionForDocumentId` method).

"Is there a better way to do this?" was more of a semi-rhetorical question to the poster of the issue.

I think what you have is a pretty sensible approach for the time being.
