### ISSUE TITLE
Feature Request: Accounts

### ISSUE THREAD

**Issue by boustanihani** [DrMongo/DrMongo#91]
Please support creating accounts so that each user has his own private connections.

**Comment by tothradoslav** [comment]
Could you please explain the usecase for private connections?

**Comment by boustanihani** [comment]
DrMongo could be used to manage dev- but also production deployments. I mean by this, when we deploy DrMongo somewhere, not everyone able to discover the URL should gain access to all databases on the system...

So better if one needs to login in order to see his connections. **Being able to share a connection with another user is also a nice feature.** So when I click "share", I can select (from a list) which users should be able to see my connection on their dashboard... What do you think?

**Comment by tothradoslav** [comment]
We have been discussing this previously as we could create an online manager at www.drmongo.com where you can create your account, add your private connections and manage them from anywhere without cloning and running your app localy (or on your own servers). 

However, at this point, since drmongo is at a very early "alfa stage", this is quite risky due to possible security attacks. You have to understand that drmongo has complete access to all data if there no role restrictions on the mongo server we connect to (for example read-only access).

Another point of view is "privacy" as drmongo processes all the viewed data, so the creators of such a service could potentially have access to all these data... Obviously, we don't want to see your data, but there could be a bug or a hacker who could...

So for this, drmongo has to evolve a bit. 

Otherwise, I agree that this could be a good feature.

**Comment by boustanihani** [comment]
I also agree with what you said, so lets just keep this open and wait till DrMongo matures :bowtie:
